### ISSUE TITLE
Message notifications

### ISSUE THREAD

**Issue by AuroraPR** [suprabathk/CLI-Interface-For-Mi-Band#2]
Hi!

I'm working on a project, and i've seen different source python codes of miband. I have a question and I though you could help me with it. 

The message notifications only allows to change the caller ID, and I want to know if you know how to change the content of the message. I need to know how to solve it.

Thanks,
Aurora.

**Comment by suprabathk** [comment]
Hello @AmsterdamVibes 

Sure, You can change the content of the notification. Take a look at the Missed call notification option. In that you can set the content to whatever you want. So, if you can change content in this, then you can change it the Default message notification also. Please take a look at the code. I'll try my level best to update it.

Feel free to write again.

Peace!
