### ISSUE TITLE
Need help 

### ISSUE THREAD

**Issue by rayavarapuvikram1** [suprabathk/CLI-Interface-For-Mi-Band#3]
I am trying to access Device event it's not happening.
I was trying from 6 months.

**Comment by suprabathk** [comment]
Hello @rayavarapuvikram1
Could you explain a the problem a little in detail.

**Comment by rayavarapuvikram1** [comment]
I am trying to access mi band touch button on the button. I am unable to do it.

**Comment by suprabathk** [comment]
@rayavarapuvikram1 
You can have a look at this [https://github.com/vshymanskyy/miband-js](url)

**Comment by rayavarapuvikram1** [comment]
I already tried and I was unable to find

**Comment by suprabathk** [comment]
Hi @rayavarapuvikram1 
The Mi Band button touch can be detected on the 2nd version of the bands i.e, Mi Band 2.
There are many apps on Playstore using this feature but they work only with Mi Band HRX and 2.
So if you are using Mi band 3 or more latest version, you cannot detect touch.

Peace!
