### ISSUE TITLE
Could I get the real-time data from acceleration sensor?

### ISSUE THREAD

**Issue by VincentJYZhang** [suprabathk/CLI-Interface-For-Mi-Band#4]
Hi,
I'm working on a project and need the real-time acceleration data. This question nagged me for many days. I really need some help.

Thanks,
Junyang

**Comment by savegame** [comment]
i think standard firmware do not send real time acceleration...

**Comment by suprabathk** [comment]
@VincentJYZhang 
By writing [0x12, 0x1] to the CONTROL_POINT characteristic, the band starts notifying on the UUID_CHARACTERISTIC_SENSOR_DATA characteristic a continuous flow of data, which I believe could be live accelerometer data.

**Comment by suprabathk** [comment]
Hello @VincentJYZhang 

Try by writing [0x12, 0x1] to the CONTROL_POINT characteristic.
The band starts sending a continuous flow of data the UUID_CHARACTERISTIC_SENSOR_DATA characteristic.
That data stream is live accelerometer data of your band.

Have a look at this
[https://github.com/Freeyourgadget/Gadgetbridge/issues/63](url)

Peace!
