### ISSUE TITLE
How can we reconnect when band comes in Bluetooth range?

### ISSUE THREAD

**Issue by sulabh9999** [suprabathk/CLI-Interface-For-Mi-Band#5]
Is there any way to reconnect already authenticated Mi Band 3 when band comes in range again? Please help.

**Comment by suprabathk** [comment]
Hi @sulabh9999 

You can make the Raspberry Pi (Or any other device your using) to scan for nearby devices and connect to the Mi Band automatically. Use `sudo hcitool lescan` for scanning.

Above process can be achieved by writing a simple Python code.

If you need further help feel free to ask.
